- name: Install packages
  hosts: localhost
  become: true
  pre_tasks:
    - name: Update Cache for Ubuntu/WSL
      tags:
      - git
      - tmux
      - zsh
      - nvim
      - stow
      - python
      - go
      - node
      ansible.builtin.apt:
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'
  tasks:
    - name: Install Packages from apt
      tags: 
      - tmux
      - git
      - stow
      - zsh
      - go
      - python
      - node
      ansible.builtin.apt: 
        name:
          - tmux
          - stow
          - git
          - zsh
          - python3
          - node
      when: ansible_facts['os_family'] == 'Debian'

    - name: Ensure Homebrew is installed
      tags:
      - git
      - neovim
      - htop
      - tmux
      - stow
      - python3
      - node
      shell: |
        if ! command -v brew &> /dev/null
        then
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
      args:
        creates: /opt/homebrew/bin/brew
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Install packages with Homebrew
      become_user: "{{ ansible_env.SUDO_USER }}"
      tags:
      - git
      - tmux
      - zsh
      - stow
      - python
      - go
      - node
      community.general.homebrew:
        name: git 
        state: present 
        name: tmux 
        state: present
        name: zsh
        state: present
        name: stow
        state: present
        name: python3
        state: present
        name: golang
        state: present
        name: node
        state: present
        update_homebrew: true
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Change Shell to zsh
      tags:
      - zsh
      shell: |
        chsh -s `which zsh`

    - name: Install ohmyzsh
      tags:
      - zsh
      shell: |
        curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh

    - name: Install zsh Plugins
      tags:
      - zsh
      ansible.builtin.git:
        repo: 'https://github.com/marlonrichert/zsh-autocomplete.git'
        dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"

    - name: Install nvim
      tags:
      - nvim
      ansible.builtin.git:
        repo: 'https://github.com/nvim-lua/kickstart.nvim.git'
        dest: "{{ lookup('env', 'XDG_CONFIG_HOME') | default(ansible_env.HOME + '/.config', true) }}/nvim"
        depth: 1
#    - name: Update zshrc
#      shell: |
#      add command to update zshrc dotfile


